/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f58",
        "error": "#ffb4ab",
        "surface-tint": "#00daf3",
        "inverse-surface": "#dae2fd",
        "on-error": "#690005",
        "primary-fixed": "#9cf0ff",
        "on-surface": "#dae2fd",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "on-secondary-container": "#a9bad3",
        "on-secondary-fixed": "#0b1c30",
        "surface": "#0b1326",
        "on-primary-container": "#0090a1",
        "on-secondary": "#213145",
        "on-primary-fixed": "#001f24",
        "error-container": "#93000a",
        "background": "#0b1326",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface-variant": "#c4c6cc",
        "on-primary": "#00363d",
        "outline": "#8e9196",
        "primary": "#00daf3",
        "inverse-on-surface": "#283044",
        "surface-variant": "#2d3449",
        "on-tertiary": "#003824",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#131b2e",
        "inverse-primary": "#006875",
        "primary-container": "#001e22",
        "outline-variant": "#44474c",
        "tertiary-fixed": "#6ffbbe",
        "secondary-container": "#3a4a5f",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#009567",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#001f12",
        "primary-fixed-dim": "#00daf3",
        "on-background": "#dae2fd",
        "surface-dim": "#0b1326",
        "on-secondary-fixed-variant": "#38485d",
        "secondary": "#b7c8e1",
        "surface-container-highest": "#2d3449",
        "secondary-fixed": "#d3e4fe"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
